(print-line (+ 2 3))
(print-line (/ 2 3))
(defun fact(n)
  (if (= n 0)
      1
    (* n (fact (- n 1)))))
(defun fact2(n)
  (let ((res 1)
        (i 1))
    (while (<= i n)
      (set 'res (* res i)
           'i (+ i 1)))
    res))
(print-line (fact 3))
(print-line (fact 100))
(print-line (fact2 3))
(print-line (fact2 100))
